export default{
    LOGIN:'LOGIN',
    SIGNUP:'SIGNUP',
    OTP_VERIFICATION:'OTP_VERIFICATION',
    EMPTY:'EMPTY',
    SCROLL_API:'SCROLL_API',
    LOGOUT:'LOGOUT',
    CLEAR_REDUX_STATE:'CLEAR_REDUX_STATE',
    CONVERSATION:'CONVERSATION'
}